name: Pipeline
on: 
  push:
   branches: 
   - main
   - master
   - develop
   - 'feature/**'
   - 'feature*'
   
   
  pull_request:
    types: [synchronize]
    branches: 
    - develop
    - master
    - main
jobs: 
  build-dev:
    if: |
      ${{  github.event.ref != 'refs/heads/main'  &&  github.event.ref != 'refs/heads/develop' }} &&
      ${{ github.event.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo feature
  build-test:
    if: |
      ${{  github.event.ref != 'refs/heads/main'  &&  github.event.ref != 'refs/heads/develop' }} &&
      ${{ github.event.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo feature
