name: Pipeline
on: 
  push:
   branches: 
   - main
   - master
   - develop
   - 'feature/**'
   - 'feature*'
   
   
  pull_request:
    types: [synchronize]
    branches: 
    - develop
    - master
    - main
jobs: 

  build-test:
    if: |
       github.event.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ./*
          key: sub
      - run: |
              echo 'feature' > text1.txt
              ls -ltr
      - uses: actions/cache@v3
        with:
          path: ./*
          key: sub
  build-prod:
    if: |
       github.event.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/cache@v3
        with:
          path: ./*
          key: sub
      - run: |
            echo 'prod' > text2.txt
            ls -ltr
      - uses: actions/cache@v3
        with:
          path: ./*
          key: sub
  build:
    if: |
       github.event.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/cache@v3
        with:
          path: ./*
          key: sub
      - run: ls -ltr
      - run: cat text1.txt
      - run: cat text2.txt
      
