name: Pipeline
on: 
  push:
   branches: 
   - main
   - master
   - develop
   - 'feature/**'
   - 'feature*'
   
   
  pull_request:
    types: [synchronize]
    branches: 
    - develop
    - master
    - main
jobs: 
  build-dev:
    if: |
       github.event.ref != 'refs/heads/main'  &&  github.event.ref != 'refs/heads/develop'  &&
       github.event.ref != 'refs/heads/master' 
    runs-on: ubuntu-latest
    steps:
      - run: echo feature
  build-test:
    if: |
       github.event.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      - run: echo 'feature' > text1.txt
      - uses: actions/cache@v3
        with:
          path: ./*
          key: sub
  build-prod:
    if: |
       github.event.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/cache@v3
        with:
          path: ./*
          key: sub
      - run: echo 'prod' > text2.txt
      - uses: actions/cache@v3
        with:
          path: ./*
          key: sub
  build:
    if: |
       github.event.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/cache@v3
        with:
          path: ./*
          key: sub
      - run: cat text1.txt
      - run: cat text2.txt
      
