name: ooo
on: 
  push:
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Subhajit" > subhajit.txt
      - uses: actions/cache@v3
        with:
          path: "./*"
          key: "${{ github.sha }}-dev"
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: "./*"
          key: "${{ github.sha }}-dev"
      - run: |
            ls -ltr
            cat subhajit.txt
