name: testing
on:
  push:
  
jobs:
  job1-f:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo ${{ github.event.repository.name }}
            echo $(basename ${{ github.event.ref }})\
            echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
            echo  ${GITHUB_REF}
            
