name: testing
on:
  push:
  
jobs:
  job1-f:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo ${{ github.event.repository.name }}
            echo $(basename ${{ github.event.ref }})
      - shell: bash
        run: |
            echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - shell: bash
        run: |
            echo  ${GITHUB_REF}
      - shell: bash
        run: |
            echo ${GITHUB_REF##*/}
            
