name: testing
on:
  push:
  
jobs:
  job1-f:
    # if: ${{ github.event.ref != 'refs/heads/master'}} && ${{ github.event.ref != 'refs/heads/main' }} && ${{ github.event.ref != 'refs/heads/develop' }}
    # if: contains(github.event.ref,master'
    if: contains(github.event.ref ,'main')
    runs-on: ubuntu-latest
    steps:
    
      - run: echo print
     
